export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";



export const POST_ASSIGNMENT_START = "POST_ASSIGNMENT_START";
export const POST_ASSIGNMENT_SUCCESS = "POST_ASSIGNMENT_SUCCESS";
export const POST_ASSIGNMENT_FAIL = "POST_ASSIGNMENT_FAIL";

export const GET_ASSIGNMENT_START = "GET_ASSIGNMENT_START";
export const GET_ASSIGNMENT_SUCCESS = "GET_ASSIGNMENT_SUCCESS";
export const GET_ASSIGNMENT_FAIL = "GET_ASSIGNMENT_FAIL";
